Add feature to ignore only some unhandled messages
JKorf/CryptoExchange.Net pull request #194
Opened 2024-03-22 08:43 UTC by Jonnern

I think setting `UnhandledMessageExpected = true` may hide too many messages. Let's say the exchange sends some messages you don't want to handle and you need to enable UnhandledMessageExpected to avoid noise in the log.

By adding the property `HashSet<string>? IgnoredUnhandledMessages` in `SocketApiClient`, you can ignore a set of unhandled messages and log the messages that are not ignored.

I added a test case where a "connected" message is ignored and "unhandled" will be logged.

2024-04-03 18:39 UTC, JKorf requested changes

2024-04-03 18:39 UTC, JKorf commented on CryptoExchange.Net/Clients/SocketApiClient.cs
> +                socketConnection.UnhandledMessage += HandleUnhandledMessage;
This is already registered when the socket is created

2024-04-16 07:25 UTC, JKorf commented
Have you encountered this to be a problem in a certain scenario?

2024-04-16 07:34 UTC, Jonnern commented
> Have you encountered this to be a problem in a certain scenario?

Yes, I made a wrapper around the CexIo API and it sends a connected message when you connect the socket
`{"e":"connected"}` [https://trade.cex.io/docs/#websocket-public-api-calls](https://trade.cex.io/docs/#websocket-public-api-calls)

As I don't want to ignore every unhandled message, I want to ignore only specific messages like this one

2024-04-16 12:45 UTC, JKorf commented
If you look at the Kraken socket client you can see that it registers a HeartbeatSubscription. It doesn't specifically have a purpose other then receiving the server sent heartbeat messages. You could do something similar which I feel is a bit cleaner way.

https://github.com/JKorf/Kraken.Net/blob/14b790ddff5d1ae76909e40d99897dca733af757/Kraken.Net/Clients/SpotApi/KrakenSocketClientSpotApi.cs#L62

2024-04-24 07:33 UTC, Jonnern commented
I forgot that I could add that as a SystemSubscription. Thanks for the advice

09:31:13:230	CexIo: Debug: [Sckt 1] connected to wss://trade.cex.io/api/spot/ws-public
09:31:13:230	CexIo: Debug: [Sckt 1] status changed from None to Connected
09:31:13:230	CexIo: Debug: [Sckt 1] starting processing tasks
09:31:13:230	CexIo: Trace: [Sckt 1] received 17 bytes in single message
09:31:13:230	CexIo: Trace: [Sckt 1] received {"e":"connected"}
09:31:13:230	CexIo: Trace: [Sckt 1] 1 processor(s) matched to message with listener identifier connected

2024-04-24 07:33 UTC, closed without merging